### ISSUE TITLE
Appx Alg: Lec 19 small typo

### ISSUE THREAD

**Issue by hessakh** [sleepymalc/Notes#6]
On page 69 in the definition of soundness, completeness should be soundness. The typo is repeated at the definition 5.1.7.

Thanks again for publishing these notes!

**Comment by sleepymalc** [comment]
I guess you're saying that the definition of soundness and completeness is flipped?

**Comment by hessakh** [comment]
No I don’t think they are flipped. It looks like the definition for soundness is saying the condition satisfies completeness when I think it should be soundness?

<img width="578" alt="Screen Shot 2022-11-13 at 8 50 43 PM" src="https://user-images.githubusercontent.com/36086865/201558721-e443b3d2-c657-4f0d-b473-48d7f40401c6.png">

**Comment by sleepymalc** [comment]
ooooh, I see. yes, let me fix this.
